# Numpy

In [1]:
import numpy as np

### Applications basiques

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get the shape and dimension
print(a.ndim)
print(a.shape)
print(b.shape)

1
(3,)
(2, 3)


In [10]:
# Get the type
a.dtype

dtype('int64')

In [ ]:
# Change the type
c = np.array([1,2,3],dtype='int16')
c.dtype

dtype('int16')

In [15]:
# Get size
a.itemsize
a.nbytes
b.itemsize

8

### Accès et modification de valeurs

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [20]:
# Get a specific element
a[0,5]
a[0,-3]

np.int64(5)

In [23]:
# Get a row or a column
a[0,:]
a[:,2]

array([ 3, 10])

In [ ]:
# [startingindex:endingindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

### Initialisation d'arrays

In [28]:
np.zeros(5)
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(5)
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# Another number
np.full((2,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [33]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Generate a random decimal number
np.random.rand()

0.45460118232263635

In [38]:
np.random.rand(4,2)
np.random.random_sample(a.shape)

array([[0.18030224, 0.1491139 , 0.6358809 , 0.78369859, 0.21678082,
        0.17009887, 0.19803668],
       [0.18012244, 0.95615591, 0.96019359, 0.94644926, 0.32397107,
        0.57543224, 0.80167041]])

In [42]:
# Random integer values
np.random.randint(7) # nombre entre 0 et 7
np.random.randint(5,10,size=(3,3))

array([[6, 6, 6],
       [6, 5, 6],
       [9, 6, 6]])

In [43]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arr = np.array([[1,2,3]])
np.repeat(arr,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
I = np.ones((5,5))
I[1:-1,1:-1] = np.zeros((3,3))
I[2,2] = 9
print(I)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Attention avec les copies

In [51]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [52]:
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [56]:
a[0] = 1
print(a)
print(b)

[1 2 3]
[1 2 3]


In [58]:
c = a.copy()
c[0] = 100
print(a)
print(c)

[1 2 3]
[100   2   3]


### Mathématiques

In [59]:
a+2

array([3, 4, 5])

In [62]:
a*2

array([2, 4, 6])

In [63]:
a/2

array([0.5, 1. , 1.5])

In [64]:
a+c

array([101,   4,   6])

In [65]:
a**2

array([1, 4, 9])

In [60]:
a.sum()

np.int64(6)

In [61]:
a.mean()

np.float64(2.0)

In [67]:
np.sin(a)
np.cos(a)
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

#### Algèbre linéaire

In [69]:
A = np.ones((2,3))
B = np.full((3,2),2)
print(A)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [72]:
C = np.matmul(A,B)
print(C)

[[6. 6.]
 [6. 6.]]


In [74]:
np.linalg.det(C)
np.linalg.det(np.identity(3))

np.float64(1.0)

#### Statistiques

In [78]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
stats.mean()

np.float64(3.5)

In [ ]:
stats.sum()       # somme de tous les éléments de la matrice
stats.sum(axis=1) # somme par lignes
stats.sum(axis=0) # somme par colonnes

array([5, 7, 9])

In [ ]:
stats.min()
stats.max()

array([4, 5, 6])

### Réorganisation des array

In [88]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [93]:
after = before.reshape((1,6))
print(after)

[[1 2 3 4 5 6]]


In [96]:
# Concaténation de vecteurs
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v = np.vstack([v1,v2])
print(v)
w = np.hstack([v1,v2])
print(w)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [100]:
(v < 5).sum()
v[(v < 5)]
((v<5) & (v>1)).sum()

np.int64(3)